#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Old version not supplied as the first argument"
  exit 1
elif [ -z "$2" ]; then
  echo "New version not supplied as the second argument"
  exit 1
fi

sed -i '' "s/$1/$2/g" DeltaDNA/DDNASettings.m DeltaDNA.podspec README.md README-CN.md buildFrameworks.sh .yamato/build.yaml

echo "Have you updated the changelog?"

