source 'https://github.com/CocoaPods/Specs'

project '../DeltaDNA'
workspace '../DeltaDNA'
#inhibit_all_warnings!

use_frameworks!

def shared_pods
    pod 'Specta', '~> 1.0.7'
    pod 'Expecta', '~> 1.0.6'
    pod 'OCHamcrest', '~> 7.1.1'
    pod 'OCMockito', '~> 5.1.1'
end

target 'DeltaDNA iOS Tests' do
    platform :ios, '9.0'
    shared_pods
end

target 'DeltaDNA tvOS Tests' do
    use_frameworks!
    platform :tvos, '9.0'
    shared_pods
end

