source 'https://github.com/CocoaPods/Specs'

project '../DeltaDNA'
workspace '../DeltaDNA'
#inhibit_all_warnings!

def shared_pods
    pod 'Specta', '~> 1.0.7'
    pod 'Expecta', '~> 1.0.6'
    pod 'OCMockito', '~> 5.0.1'
end

target 'DeltaDNA iOS Tests' do
    platform :ios, '8.0'
    shared_pods
end

target 'DeltaDNA tvOS Tests' do
    use_frameworks!
    platform :tvos, '9.0'
    shared_pods
end

# Enable extra logging
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'DeltaDNA'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DDNA_DEBUG=1'
            end
        end
    end
end
